# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Post.create! title: "Overheard on Kahled's Snapchat", body: " You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed. They don’t want us to win. Bless up. Stay focused. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. To be successful you’ve got to work hard, to make history, simple, you’ve got to make it. Surround yourself with angels, positive energy, beautiful people, beautiful souls, clean heart, angel. You see that bamboo behind me though, you see that bamboo? Ain’t nothin’ like bamboo. Bless up. <br/>

To succeed you must believe. When you believe, you will succeed. Mogul talk. I told you all this before, when you have a swimming pool, do not use chlorine, use salt water, the healing, salt water is the healing. Wraith talk. Give thanks to the most high. I’m up to something. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. Lion! Learning is cool, but knowing is better, and I know the key to success. I’m giving you cloth talk, cloth. Special cloth alert, cut from a special cloth. The key to more success is to get a massage once a week, very important, major key, cloth talk.

We don’t see them, we will never see them. You see that bamboo behind me though, you see that bamboo? Ain’t nothin’ like bamboo. Bless up. Congratulations, you played yourself. The key to more success is to get a massage once a week, very important, major key, cloth talk. Egg whites, turkey sausage, wheat toast, water. Of course they don’t want us to eat our breakfast, so we are going to enjoy our breakfast. Wraith talk. You should never complain, complaining is a weak emotion, you got life, we breathing, we blessed.

You smart, you loyal, you a genius. We don’t see them, we will never see them. Look at the sunset, life is amazing, life is beautiful, life is what you make it. Mogul talk. A major key, never panic. Don’t panic, when it gets crazy and rough, don’t panic, stay calm. Every chance I get, I water the plants, Lion! How’s business? Boomin. Hammock talk come soon. The key is to drink coconut, fresh coconut, trust me."

Post.create! title: "Overheard at Blackhole", body:"Put a bird on it roof party XOXO, polaroid shabby chic pitchfork locavore fixie twee williamsburg intelligentsia lomo paleo sartorial. Shoreditch flexitarian tacos, banh mi whatever hammock portland. Green juice mixtape cliche, bushwick asymmetrical art party YOLO kitsch viral lomo everyday carry disrupt cardigan seitan. Crucifix pug chartreuse yr. Lumbersexual banjo distillery, yuccie gluten-free tofu pabst man braid jean shorts. Bushwick synth irony shoreditch try-hard farm-to-table. Meggings intelligentsia wolf master cleanse, flexitarian neutra wayfarers art party kickstarter cliche artisan.

Literally tousled dreamcatcher heirloom. Ethical schlitz cornhole fanny pack pug, selvage gentrify. Yuccie everyday carry normcore, man braid fanny pack kogi salvia venmo cronut kombucha put a bird on it 8-bit humblebrag irony. Church-key neutra leggings distillery four loko polaroid umami, etsy meggings banh mi affogato plaid typewriter migas. Forage organic four loko neutra, poutine 3 wolf moon humblebrag banjo mixtape hashtag tilde keffiyeh. Pop-up offal gluten-free, put a bird on it swag pug chia pork belly single-origin coffee man braid migas blue bottle. Franzen squid tilde fap selvage, kale chips mixtape messenger bag hashtag pop-up sriracha deep v sustainable austin.

Beard truffaut blog forage leggings quinoa, jean shorts banjo. Seitan bitters gastropub gochujang, gentrify you probably haven't heard of them fashion axe kitsch vinyl 3 wolf moon kickstarter whatever forage. Trust fund affogato bitters pour-over paleo cray. Drinking vinegar williamsburg post-ironic dreamcatcher next level. Ennui hella salvia, XOXO crucifix cold-pressed bicycle rights. Wolf asymmetrical heirloom echo park sustainable. Four dollar toast mustache hammock scenester, thundercats quinoa tousled godard flexitarian fashion axe irony hashtag fanny pack.<br/>

Organic butcher celiac XOXO, irony stumptown green juice umami gentrify marfa lomo ennui. You probably haven't heard of them microdosing asymmetrical, normcore stumptown selfies organic art party vegan post-ironic. Before they sold out wayfarers locavore tofu, celiac flannel humblebrag gastropub venmo YOLO migas meggings bitters williamsburg. VHS wayfarers pork belly, dreamcatcher messenger bag organic umami cliche etsy art party meggings four loko mixtape. Tumblr bushwick man braid, hammock skateboard selfies stumptown semiotics truffaut kitsch bitters health goth. Man bun truffaut wayfarers skateboard, helvetica listicle slow-carb. Fap swag slow-carb bespoke."

Post.create! title: "Overheard at Station Houston", body:"Backing crowdsource disruptive bandwidth business-to-consumer iPhone virality startup ownership stealth. Ecosystem long tail A/B testing gen-z innovator. Value proposition return on investment virality branding supply chain non-disclosure agreement gen-z seed round infrastructure social proof business model canvas hypotheses. Bootstrapping focus termsheet client influencer vesting period disruptive business-to-consumer. Focus angel investor freemium startup. Pivot burn rate leverage equity founders. Creative funding innovator business model canvas graphical user interface learning curve infrastructure beta buyer focus lean startup agile development. Launch party deployment churn rate direct mailing pitch non-disclosure agreement agile development hackathon network effects prototype series A financing infrastructure crowdsource first mover advantage. Beta user experience innovator angel investor pivot seed round low hanging fruit first mover advantage creative churn rate return on investment non-disclosure agreement marketing. Social proof supply chain stealth product management series A financing angel investor social media business-to-consumer partnership success backing stock beta MVP.

Equity leverage seed money assets value proposition MVP iPad holy grail startup. Validation creative focus vesting period supply chain entrepreneur angel investor. Focus branding marketing iPhone user experience buyer startup non-disclosure agreement interaction design founders. Strategy hypotheses bootstrapping buyer crowdfunding. Innovator rockstar buyer partnership channels low hanging fruit validation alpha pivot assets user experience market non-disclosure agreement first mover advantage. Bootstrapping scrum project handshake gen-z partnership disruptive ramen investor supply chain learning curve return on investment. Ecosystem incubator mass market angel investor interaction design deployment user experience conversion innovator early adopters. Conversion first mover advantage channels. Advisor conversion release paradigm shift infrastructure channels strategy growth hacking iteration low hanging fruit gen-z. Startup android accelerator virality social media low hanging fruit freemium launch party interaction design strategy.

Market release lean startup supply chain agile development creative gamification. Metrics iteration marketing series A financing return on investment stock bandwidth growth hacking ecosystem startup monetization early adopters niche market. Scrum project client stock. IPad accelerator ramen direct mailing. Responsive web design deployment beta analytics. Innovator market seed round A/B testing paradigm shift growth hacking virality ramen assets pivot vesting period bandwidth conversion. Niche market entrepreneur handshake deployment seed money conversion strategy. Low hanging fruit advisor buzz graphical user interface. Success buzz analytics burn rate bootstrapping gamification. Crowdfunding social proof infographic freemium equity investor partnership traction supply chain launch party startup.

Mass market churn rate traction assets. Bootstrapping lean startup beta focus startup mass market value proposition android. Social media scrum project crowdfunding leverage branding seed money incubator value proposition technology customer holy grail assets. Return on investment series A financing ownership ecosystem ramen. Growth hacking advisor ramen business model canvas A/B testing user experience business-to-consumer. Supply chain ecosystem client creative monetization accelerator disruptive stealth iPad ramen assets success. Ecosystem social proof first mover advantage deployment lean startup pivot research & development ramen. Agile development venture direct mailing. Business-to-consumer creative technology agile development bandwidth A/B testing customer equity seed round return on investment mass market crowdfunding series A financing stealth. IPad release advisor agile development innovator incubator scrum project analytics social proof product management success.

Customer gen-z branding partner network business plan analytics channels release churn rate vesting period. Deployment creative interaction design conversion strategy seed round success social media. Startup monetization pitch angel investor funding gamification rockstar. Partner network innovator scrum project launch party creative series A financing vesting period. Ownership founders conversion MVP hypotheses crowdsource launch party low hanging fruit startup business-to-consumer prototype business-to-business stock metrics. Venture sales channels termsheet supply chain return on investment twitter. Android MVP freemium. Conversion seed money pitch. Growth hacking hackathon ecosystem stock business model canvas beta. Rockstar partner network learning curve direct mailing user experience vesting period incubator interaction design validation sales handshake iPad."
Post.create! title: "Overheard at Space Center Houston", body:"Dinosaurs are extinct today because they lacked opposable thumbs and the brainpower to build a space program.

Across the sea of space, the stars are other suns.

That's one small step for [a] man, one giant leap for mankind.

Here men from the planet Earth first set foot upon the Moon. July 1969 AD. We came in peace for all mankind.

Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next 10."

Post.create! title: "Overheard at The Black Lab", body: " Never, never assume that what you have achieved is fucking good enough. The details are not the details. They make the fucking design. Widows and orphans are terrible fucking tragedies, both in real life and definitely in typography. If you fucking give up, you will achieve nothing. While having drinks with Tibor Kalman one night, he told me, &ldquo;When you make something no one hates, no one fucking loves it.&rdquo;

Remember it’s called the creative process, it’s not the creative fucking moment. Nothing of value comes to you without fucking working at it. Think about all the fucking possibilities. Practice won’t get you anywhere if you mindlessly fucking practice the same thing. Change only occurs when you work deliberately with purpose toward a goal. Make your work consistent but not fucking predictable. You won’t get good at anything by doing it a lot fucking aimlessly. Remember it’s called the creative process, it’s not the creative fucking moment. Remember it’s called the creative process, it’s not the creative fucking moment.

A good fucking composition is the result of a hierarchy consisting of clearly contrasting elements set with distinct alignments containing irregular intervals of negative space. Design as if your fucking life depended on it. To surpass others is fucking tough, if you only do as you are told you don’t have it in you to succeed. Never let your guard down by thinking you’re fucking good enough.

Saul Bass on failure: Failure is built into creativity… the creative act involves this element of ‘newness’ and ‘experimentalism,’ then one must expect and accept the fucking possibility of failure. Don’t worry about what other people fucking think. The details are not the details. They make the fucking design. Never, never assume that what you have achieved is fucking good enough. When you sit down to work, external critics aren’t the enemy. It’s you who you must to fight against to do great fucking work. You must overcome yourself. Don’t worry about what other people fucking think.

Respect your fucking craft. Sometimes it is appropriate to place various typographic elements on the outside of the fucking left margin of text to maintain a strong vertical axis. This practice is referred to as exdenting and is most often used with bullets and quotations. Don’t fucking lie to yourself. Respect your fucking craft. Design is all about fucking relationships&mdash;the relationship of form and content, the relationship of elements, the relationship  of designer and user.

"
